## TPR confidence interval plots

In [1]:
import pandas as pd
import numpy as np
from statistics import mean

import matplotlib.pyplot as plt

diseases = ['Airspace Opacity', 'Atelectasis', 'Cardiomegaly',
       'Consolidation', 'Edema', 'Enlarged Cardiomediastinum', 'Fracture',
       'Lung Lesion', 'No Finding', 'Pleural Effusion', 'Pleural Other',
       'Pneumonia', 'Pneumothorax', 'Support Devices']

diseases_abbr = {'Cardiomegaly': 'Cd',
                'Effusion': 'Ef',
                'Enlarged Cardiomediastinum': 'EC',
                'Lung Lesion': 'LL',
                'Atelectasis': 'A',
                'Pneumonia': 'Pa',
                'Pneumothorax': 'Px',
                'Consolidation': 'Co',
                'Edema': 'Ed',
                'Pleural Effusion': 'Ef',
                'Pleural Other': 'PO',
                'Fracture': 'Fr',
                'Support Devices': 'SD',
                'Airspace Opacity': 'AO',
                'No Finding': 'NF'
                }

## Percentages

In [2]:
train_df_path ="/scratch/gobi2/projects/ml4h/datasets/new_split/8-1-1/new_train.csv"
test_df_path ="/scratch/gobi2/projects/ml4h/datasets/new_split/8-1-1/new_test.csv"
val_df_path = "/scratch/gobi2/projects/ml4h/datasets/new_split/8-1-1/new_valid.csv"
val_df = pd.read_csv(val_df_path)
train_df = pd.read_csv(train_df_path)
test_df = pd.read_csv(test_df_path)

In [3]:
WholeData = test_df.append([val_df, train_df])

In [5]:
print("Number of images:",len(WholeData) )
Whole =WholeData.groupby("subject_id")
print("Number of unique patients:",len(Whole.count()) )

Number of images: 371858
Number of unique patients: 65079

In [6]:
WholeDataX =WholeData.groupby("gender")
WholeDataX_df = WholeDataX.describe()
WholeDataX_df

       subject_id                                                      \
            count          mean           std         min         25%
gender
F        177853.0  1.499090e+07  2.883554e+06  10000032.0  12489621.0
M        194005.0  1.501641e+07  2.879538e+06  10000764.0  12493783.0

                                           No Finding       ... Fracture       \
               50%         75%         max      count mean  ...      75%  max
gender                                                      ...
F       14985054.0  17503573.0  19999987.0    72846.0  1.0  ...      1.0  1.0
M       15053729.0  17487765.0  19999442.0    68734.0  1.0  ...      1.0  1.0

       Support Devices
                 count      mean       std  min  25%  50%  75%  max
gender
F              36680.0  0.932361  0.267733 -1.0  1.0  1.0  1.0  1.0
M              52231.0  0.938044  0.257066 -1.0  1.0  1.0  1.0  1.0

[2 rows x 120 columns]

In [7]:
dfWhole_Sex = WholeDataX_df["subject_id"]['count']
total_CXP= dfWhole_Sex["F"]+dfWhole_Sex["M"]
Male_percent = 100*dfWhole_Sex["M"]/total_CXP
print("Male Percent:  ",Male_percent)

print("female Percent:  ",100*dfWhole_Sex["F"]/total_CXP)
print("#images",total_CXP)

Male Percent:   52.17179676112925
female Percent:   47.82820323887075
#images 371858.0

In [8]:
WholeData['gender'].value_counts()

M    194005
F    177853
Name: gender, dtype: int64

In [9]:
train_df_path ="/scratch/gobi2/projects/ml4h/datasets/new_split/8-1-1/new_train.csv"
test_df_path ="/scratch/gobi2/projects/ml4h/datasets/new_split/8-1-1/new_test.csv"
val_df_path = "/scratch/gobi2/projects/ml4h/datasets/new_split/8-1-1/new_valid.csv"
val_df = pd.read_csv(val_df_path)
train_df = pd.read_csv(train_df_path)
test_df = pd.read_csv(test_df_path)

In [10]:
def preprocess_MIMIC(split):
    
    details = pd.read_csv("/scratch/gobi2/projects/ml4h/datasets/new_split/mimic-cxr-metadata-detail.csv")
    details = details.drop(columns=['dicom_id', 'study_id', 'religion', 'marital_status', 'gender'])
    details.drop_duplicates(subset="subject_id", keep="first", inplace=True)
    df = pd.merge(split, details)
    
    copy_sunbjectid = df['subject_id'] 
    df.drop(columns = ['subject_id'])
    
    df = df.replace(
            [[None], -1, "[False]", "[True]", "[ True]", 'UNABLE TO OBTAIN', 'UNKNOWN', 'MARRIED', 'LIFE PARTNER',
             'DIVORCED', 'SEPARATED', '0-10', '10-20', '20-30', '30-40', '40-50', '50-60', '60-70', '70-80', '80-90',
             '>=90'],
            [0, 0, 0, 1, 1, 0, 0, 'MARRIED/LIFE PARTNER', 'MARRIED/LIFE PARTNER', 'DIVORCED/SEPARATED',
             'DIVORCED/SEPARATED', '0-20', '0-20', '20-40', '20-40', '40-60', '40-60', '60-80', '60-80', '80-', '80-'])
    
    df['subject_id'] = copy_sunbjectid
    df['Age'] = df["age_decile"]
    df['Sex'] = df["gender"]
    df = df.drop(columns=["age_decile", 'gender'])

    
    return df

In [11]:
test_df = preprocess_MIMIC(test_df)
train_df = preprocess_MIMIC(train_df)
val_df = preprocess_MIMIC(val_df)
WholeData = test_df.append([val_df, train_df])

In [12]:
WholeDataX =WholeData.groupby("Sex")
WholeDataX_df = WholeDataX.describe()
WholeDataX_df

    subject_id                                                      \
         count          mean           std         min         25%
Sex
F     177853.0  1.499090e+07  2.883554e+06  10000032.0  12489621.0
M     194005.0  1.501641e+07  2.879538e+06  10000764.0  12493783.0

                                        No Finding            ... Fracture  \
            50%         75%         max      count      mean  ...      75%
Sex                                                           ...
F    14985054.0  17503573.0  19999987.0   177853.0  0.409585  ...      0.0
M    15053729.0  17487765.0  19999442.0   194005.0  0.354290  ...      0.0

         Support Devices
     max           count      mean       std  min  25%  50%  75%  max
Sex
F    1.0        177853.0  0.193176  0.394791  0.0  0.0  0.0  0.0  1.0
M    1.0        194005.0  0.253617  0.435082  0.0  0.0  0.0  1.0  1.0

[2 rows x 120 columns]

In [13]:
dfWhole_Sex = WholeDataX_df["subject_id"]['count']
total_CXP= dfWhole_Sex["F"]+dfWhole_Sex["M"]
Male_percent = 100*dfWhole_Sex["M"]/total_CXP
print("Male Percent:  ",Male_percent)

print("female Percent:  ",100*dfWhole_Sex["F"]/total_CXP)
print("#images",total_CXP)

Male Percent:   52.17179676112925
female Percent:   47.82820323887075
#images 371858.0

In [14]:
WholeData_Age = WholeData[WholeData.Age != 0]
WholeDataAge =WholeData_Age.groupby("Age")
WholeDataAge_df = WholeDataAge.describe()
WholeDataAge_df

      subject_id                                                      \
           count          mean           std         min         25%
Age
0-20      8181.0  1.508950e+07  2.894724e+06  10002157.0  12641071.0
20-40    72516.0  1.502293e+07  2.891342e+06  10001038.0  12532170.0
40-60   138247.0  1.497541e+07  2.865755e+06  10000032.0  12473093.0
60-80   126799.0  1.501545e+07  2.894507e+06  10000898.0  12457153.0
80-      25877.0  1.501857e+07  2.869053e+06  10000764.0  12591968.0

                                          No Finding            ... Fracture  \
              50%         75%         max      count      mean  ...      75%
Age                                                             ...
0-20   15172839.0  17632697.0  19999733.0     8181.0  0.705293  ...      0.0
20-40  14993854.0  17518261.5  19999270.0    72516.0  0.580065  ...      0.0
40-60  14976423.0  17421577.0  19999987.0   138247.0  0.403379  ...      0.0
60-80  15056964.0  17536303.0  19999287.0   126799.0  0.261524  ...      0.0
80-    15093387.0  17530381.0  19998497.0    25877.0  0.183329  ...      0.0

           Support Devices
       max           count      mean       std  min  25%  50%  75%  max
Age
0-20   1.0          8181.0  0.089353  0.285271  0.0  0.0  0.0  0.0  1.0
20-40  1.0         72516.0  0.157703  0.364465  0.0  0.0  0.0  0.0  1.0
40-60  1.0        138247.0  0.218826  0.413452  0.0  0.0  0.0  0.0  1.0
60-80  1.0        126799.0  0.267636  0.442729  0.0  0.0  0.0  1.0  1.0
80-    1.0         25877.0  0.275843  0.446947  0.0  0.0  0.0  1.0  1.0

[5 rows x 120 columns]

In [15]:
dfWhole_Age1 = WholeDataAge_df["subject_id"]['count']
total_CXR = WholeDataAge_df["subject_id"]['count'].sum()
Age1 = round(100*(dfWhole_Age1["0-20"])/total_CXR,2)
Age2 = round(100*(dfWhole_Age1["20-40"])/total_CXR,2)
Age3 = round(100*(dfWhole_Age1["40-60"])/total_CXR,2)
Age4 = round(100*(dfWhole_Age1["60-80"])/total_CXR,2)
Age5 = round(100*(dfWhole_Age1["80-"])/total_CXR,2)
print("0-20 Percent:  ",Age1)
print("20-40 Percent:  ",Age2)
print("40-60 Percent:  ",Age3)
print("60-80 Percent:  ",Age4)
print("80- Percent:  ",Age5)
2.2+ 19.51+37.20+34.12+6.96

0-20 Percent:   2.2
20-40 Percent:   19.51
40-60 Percent:   37.2
60-80 Percent:   34.12
80- Percent:   6.96

99.99

In [16]:
2.2+ 19.51+37.20+34.12+6.96

99.99

In [17]:
WholeData_ins = WholeData[WholeData.insurance != 0]
WholeDataI =WholeData_ins.groupby("insurance")
WholeDataI_df = WholeDataI.describe()
total_CXR = WholeDataI_df["subject_id"]['count'].sum()
dfWhole_Ins = WholeDataI_df["subject_id"]['count']
Ins1 = 100*(dfWhole_Ins["Medicare"])/total_CXR
Ins2 = 100*(dfWhole_Ins["Medicaid"])/total_CXR
Ins3 = 100*(dfWhole_Ins["Other"])/total_CXR

print("Medicare Percent:  ",Ins1)
print("Medicaid Percent:  ",Ins2)
print("Other Percent:  ",Ins3)

46.07 + 8.98 + 44.95

Medicare Percent:   46.07218293015006
Medicaid Percent:   8.977604745468328
Other Percent:   44.95021232438161

100.0

In [18]:
WholeData_Rac = WholeData[WholeData.race != 0]
WholeDataR =WholeData_Rac.groupby("race")
WholeDataR_df = WholeDataR.describe()
WholeDataR_df

                              subject_id                              \
                                   count          mean           std
race
AMERICAN INDIAN/ALASKA NATIVE      761.0  1.501666e+07  2.823667e+06
ASIAN                             8479.0  1.508827e+07  2.851218e+06
BLACK/AFRICAN AMERICAN           48595.0  1.497838e+07  2.896457e+06
HISPANIC/LATINO                  16760.0  1.498038e+07  2.887127e+06
OTHER                            10010.0  1.508103e+07  2.991056e+06
WHITE                           176837.0  1.501440e+07  2.877738e+06

                                                                               \
                                      min         25%         50%         75%
race
AMERICAN INDIAN/ALASKA NATIVE  10248673.0  12493668.0  14382048.0  18116591.0
ASIAN                          10005329.0  12567919.0  15206209.0  17651038.0
BLACK/AFRICAN AMERICAN         10000935.0  12468956.0  14936098.0  17479533.0
HISPANIC/LATINO                10011607.0  12373624.0  15056964.0  17421215.0
OTHER                          10003637.0  12408654.0  15014371.0  17792682.0
WHITE                          10000032.0  12515419.0  15067471.0  17481338.0

                                          No Finding            ... Fracture  \
                                      max      count      mean  ...      75%
race                                                            ...
AMERICAN INDIAN/ALASKA NATIVE  19998198.0      761.0  0.314060  ...      0.0
ASIAN                          19990563.0     8479.0  0.326454  ...      0.0
BLACK/AFRICAN AMERICAN         19999287.0    48595.0  0.413787  ...      0.0
HISPANIC/LATINO                19983948.0    16760.0  0.451014  ...      0.0
OTHER                          19979173.0    10010.0  0.329870  ...      0.0
WHITE                          19999733.0   176837.0  0.305954  ...      0.0

                                   Support Devices                           \
                               max           count      mean       std  min
race
AMERICAN INDIAN/ALASKA NATIVE  1.0           761.0  0.392904  0.488717  0.0
ASIAN                          1.0          8479.0  0.286472  0.452139  0.0
BLACK/AFRICAN AMERICAN         1.0         48595.0  0.182426  0.386199  0.0
HISPANIC/LATINO                1.0         16760.0  0.186277  0.389342  0.0
OTHER                          1.0         10010.0  0.307592  0.461520  0.0
WHITE                          1.0        176837.0  0.281219  0.449596  0.0


                               25%  50%  75%  max
race
AMERICAN INDIAN/ALASKA NATIVE  0.0  0.0  1.0  1.0
ASIAN                          0.0  0.0  1.0  1.0
BLACK/AFRICAN AMERICAN         0.0  0.0  0.0  1.0
HISPANIC/LATINO                0.0  0.0  0.0  1.0
OTHER                          0.0  0.0  1.0  1.0
WHITE                          0.0  0.0  1.0  1.0

[6 rows x 120 columns]

In [19]:
WholeData_Rac = WholeData[WholeData.race != 0]
WholeDataR =WholeData_Rac.groupby("race")
WholeDataR_df = WholeDataR.describe()
total_CXR = WholeDataR_df["subject_id"]['count'].sum()
dfWhole_Race = WholeDataR_df["subject_id"]['count']
Rac1 = 100*(dfWhole_Race["WHITE"])/total_CXR
Rac2 = 100*(dfWhole_Race["BLACK/AFRICAN AMERICAN"])/total_CXR
Rac3 = 100*(dfWhole_Race["OTHER"])/total_CXR
Rac4 = 100*(dfWhole_Race["ASIAN"])/total_CXR
Rac5 = 100*(dfWhole_Race["HISPANIC/LATINO"])/total_CXR
Rac6 = 100*(dfWhole_Race["AMERICAN INDIAN/ALASKA NATIVE"])/total_CXR

print("WHITE Percent:  ",round( Rac1,2))
print("BLACK/AFRICAN AMERICAN Percent:  ",round(Rac2,2))
print("OTHER Percent:  ",round(Rac3,2))
print("ASIAN Percent:  ",round(Rac4,2))
print("HISPANIC/LATINO Percent:  ",round(Rac5,2))
print("AMERICANÂ INDIAN/ALASKAÂ NATIVE Percent:  ",round(Rac6,2))
print("Unkhonwn or unable to obtain Percent:  ",round(100- (Rac1 + Rac2 + Rac3 +Rac4 + Rac5 + Rac6),2))

Rac1 + Rac2 + Rac3 +Rac4 + Rac5 + Rac6

WHITE Percent:   67.64
BLACK/AFRICAN AMERICAN Percent:   18.59
OTHER Percent:   3.83
ASIAN Percent:   3.24
HISPANIC/LATINO Percent:   6.41
AMERICANÂ INDIAN/ALASKAÂ NATIVE Percent:   0.29
Unkhonwn or unable to obtain Percent:   0.0

99.99999999999999

## AUC over 5 run

In [99]:
Eval5 = pd.read_csv("./results77/Eval5.csv")
Eval4 = pd.read_csv("./results19/Eval4.csv")
Eval3 = pd.read_csv("./results38/Eval3.csv")
Eval2 = pd.read_csv("./results47/Eval2.csv")
Eval1 = pd.read_csv("./results31/Eval1.csv")

In [100]:

Evalall = Eval1[['label','auc']]

Evalall["auc2"]=Eval2['auc']
Evalall["auc3"]=Eval3['auc']
Evalall["auc4"]=Eval4['auc']
Evalall["auc5"]=Eval5['auc']
Evalall

,label,auc,auc2,auc3,auc4,auc5
0,Airspace Opacity,0.784405,0.783839,0.781926,0.780642,0.780812
1,Atelectasis,0.837631,0.837549,0.836750,0.835749,0.835974
2,Cardiomegaly,0.829379,0.829341,0.826660,0.827601,0.824610
3,Consolidation,0.844549,0.845112,0.843367,0.843544,0.842740
4,Edema,0.905035,0.905858,0.904471,0.903695,0.900561
5,Enlarged Cardiomediastinum,0.760054,0.752302,0.759163,0.753896,0.760663
6,Fracture,0.719671,0.707227,0.717175,0.729794,0.718162
7,Lung Lesion,0.770842,0.779997,0.777454,0.767263,0.764300
8,No Finding,0.870459,0.869439,0.868266,0.868240,0.865947
9,Pleural Effusion,0.934543,0.933334,0.933444,0.932899,0.932870
10,Pleural Other,0.846678,0.844375,0.844465,0.850399,0.851938
11,Pneumonia,0.756371,0.752520,0.743133,0.744188,0.744526
12,Pneumothorax,0.904925,0.902275,0.904440,0.899509,0.902842
13,Support Devices,0.927627,0.927442,0.927050,0.926168,0.925919

In [101]:
Evala_dis =Evalall.groupby("label")

In [102]:
round(Evalall.mean(axis=0),3)

auc     0.835
auc2    0.834
auc3    0.833
auc4    0.833
auc5    0.832
dtype: float64

In [103]:
print("MIMIC Mean of 14 aucs mean over 5 run:     ",round(Evalall.mean(axis=0).mean(),3))
print("MIMIC Confidence interval of 14 aucs mean over 5 run:   ",round(1.96 * Evalall.mean(axis=0).std()/np.sqrt(5) ,3 ) )

MIMIC Mean of 14 aucs mean over 5 run:      0.834
MIMIC Confidence interval of 14 aucs mean over 5 run:    0.001

In [104]:
print("MIMIC Mean of auce per disease over 5 run:     ")
round(Evalall.mean(axis=1),3)

MIMIC Mean of auce per disease over 5 run:

0     0.782
1     0.837
2     0.828
3     0.844
4     0.904
5     0.757
6     0.718
7     0.772
8     0.868
9     0.933
10    0.848
11    0.748
12    0.903
13    0.927
dtype: float64

In [105]:
print("MIMIC Confidence interval of auce per disease over 5 run:     ")
round(1.96 * Evalall.std(axis=1)/ np.sqrt(5),3)

MIMIC Confidence interval of auce per disease over 5 run:

0     0.002
1     0.001
2     0.002
3     0.001
4     0.002
5     0.003
6     0.007
7     0.006
8     0.001
9     0.001
10    0.003
11    0.005
12    0.002
13    0.001
dtype: float64